### ISSUE TITLE
Typo in footer.pug

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch.io#5]
In `/src/views/components/footer.pug` _line 15_  it should be Mastodon instead of Mastadon.

`a.footer-link(href='https://mastodon.rocks/@Ubports') Mastadon`

**Comment by NeoTheThird** [comment]
that is specific, could you send a pr? ;)

**Comment by advocatux** [comment]
Done

**Comment by NeoTheThird** [comment]
thanks
